[package]
name = "httprunner"
version = "0.1.0"
edition = "2021"
authors = ["Christian Helle"]
description = "HTTP File Runner - Execute HTTP requests from .http files"
license = "MIT"

[dependencies]
native-tls = "0.2"
serde_json = "1.0"
colored = "3.0.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.5"

[build-dependencies]
chrono = "0.4"
